name: hyperx_wallet
description: "Hyper-X Blockchain Wallet"
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  provider: ^6.0.0
  shared_preferences: ^2.0.5

flutter:
  assets:
    - assets/icon.png
